#!/usr/bin/env bash
# Roll back to a previously-pushed image version.
#
# Lists recent ECR tags for the frontend repo (the two repos are deployed in
# lockstep, so a tag exists in both or neither), prompts for the tag to roll
# back to, rewrites infra/aws/versions.auto.tfvars, and runs `terraform apply`.
#
# No rebuild, no test re-run — same exact image bytes that ran before.
#
# Required env (in infra/docker/.env or shell): same as build-and-push.sh
#   AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
#   AWS_ACCOUNT_ID, BACKEND_REPO, FRONTEND_REPO
#
# Optional env:
#   ROLLBACK_TAG    — skip the prompt, use this tag directly
#   SHOW_LIMIT      — number of recent tags to list (default: 20)
#   SKIP_TERRAFORM  — set to 1 to write versions.auto.tfvars but skip apply
#   TF_DIR          — terraform directory (default: infra/aws)

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"

if [[ -f "$SCRIPT_DIR/.env" ]]; then
  set -a; # shellcheck disable=SC1091
  source "$SCRIPT_DIR/.env"; set +a
fi

log()  { printf '\033[1;36m[%s]\033[0m %s\n' "$1" "$2"; }
fail() { printf '\033[1;31m[%s]\033[0m %s\n' "$1" "$2" >&2; }

require_env() {
  local missing=()
  for v in "$@"; do
    [[ -z "${!v:-}" ]] && missing+=("$v")
  done
  if (( ${#missing[@]} > 0 )); then
    fail "env" "missing required: ${missing[*]}"
    exit 64
  fi
}

require_cmd() { command -v "$1" >/dev/null 2>&1 || { fail "deps" "missing $1"; exit 127; }; }

require_cmd aws
require_env AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION \
            AWS_ACCOUNT_ID BACKEND_REPO FRONTEND_REPO

ECR_HOST="${ECR_HOST:-${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com}"
SHOW_LIMIT="${SHOW_LIMIT:-20}"
TF_DIR="${TF_DIR:-infra/aws}"

# ---------- 1. pick a tag ----------
if [[ -n "${ROLLBACK_TAG:-}" ]]; then
  TAG="$ROLLBACK_TAG"
  log "tag" "using ROLLBACK_TAG=$TAG (skipping prompt)"
else
  log "list" "fetching last $SHOW_LIMIT $FRONTEND_REPO tags from ECR..."
  # Sort newest-first server-side via JMESPath reverse() so the script does
  # not need `tac` (Linux-only; macOS and Git Bash on Windows do not have it).
  # Capture the full output into a variable BEFORE piping through head — a
  # naked `aws ... | head -n N` triggers SIGPIPE on aws once head exits,
  # which combined with `set -o pipefail` would fail the whole script.
  images_text="$(
    aws ecr describe-images \
      --repository-name "$FRONTEND_REPO" \
      --region "$AWS_REGION" \
      --query 'reverse(sort_by(imageDetails,&imagePushedAt))[*].[imageTags,imagePushedAt]' \
      --output text
  )" || { fail "list" "aws ecr describe-images failed"; exit 1; }

  echo
  printf '  %-32s  %-22s\n' 'TAG' 'PUSHED (UTC)'
  printf '  %-32s  %-22s\n' '-------------------------------' '----------------------'
  echo "$images_text" \
    | head -n "$SHOW_LIMIT" \
    | while IFS=$'\t' read -r tags pushed; do
        # tags column may be "v2026-04-30-abc1234 latest" — show only v* tags
        for t in $tags; do
          if [[ "$t" == v* ]]; then
            printf '  %-32s  %-22s\n' "$t" "${pushed%%.*}"
            break
          fi
        done
      done
  echo
  read -r -p "Tag to roll back to (e.g. v2026-04-30-a1b2c3d): " TAG
  [[ -z "$TAG" ]] && { fail "tag" "no tag entered — aborting"; exit 1; }
fi

# ---------- 2. verify tag exists in BOTH repos ----------
for repo in "$FRONTEND_REPO" "$BACKEND_REPO"; do
  if ! aws ecr describe-images \
        --repository-name "$repo" \
        --region "$AWS_REGION" \
        --image-ids imageTag="$TAG" >/dev/null 2>&1; then
    fail "verify" "tag $TAG not found in repo $repo — aborting"
    exit 1
  fi
done
log "verify" "tag $TAG exists in both repos"

# ---------- 3. rewrite versions.auto.tfvars ----------
VERSIONS_FILE="$REPO_ROOT/infra/aws/versions.auto.tfvars"
log "tfvars" "rewriting $VERSIONS_FILE -> $TAG"
cat > "$VERSIONS_FILE" <<EOF
# =============================================================================
# Image-tag manifest — auto-generated by infra/docker/rollback.sh
# (last run: $(date -u +%Y-%m-%dT%H:%M:%SZ) by $(whoami 2>/dev/null || echo unknown)).
# This is a ROLLBACK to a previously-deployed tag.
# =============================================================================
frontend_image = "${ECR_HOST}/${FRONTEND_REPO}:${TAG}"
backend_image  = "${ECR_HOST}/${BACKEND_REPO}:${TAG}"
EOF

# ---------- 4. terraform apply ----------
if [[ "${SKIP_TERRAFORM:-}" == "1" ]]; then
  log "tf" "SKIP_TERRAFORM=1 — skipping apply (file written, not deployed)"
else
  require_cmd terraform
  log "tf" "running 'terraform apply' in $TF_DIR (you will be prompted to type 'yes')"
  TF_RC=0
  ( cd "$REPO_ROOT/$TF_DIR" && terraform apply ) || TF_RC=$?
  if [[ $TF_RC -ne 0 ]]; then
    fail "tf" "terraform apply failed (rc=$TF_RC)"
    exit 1
  fi
fi

# ---------- 5. append to deploy log ----------
DEPLOY_LOG="$SCRIPT_DIR/deployments.log"
DEPLOY_BY="$(whoami 2>/dev/null || echo unknown)"
DEPLOY_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf '%s\t%s\t%s\t%s\t%s\n' \
  "$DEPLOY_TS" "rollback" "$TAG" "$DEPLOY_BY" "rolled back via rollback.sh" \
  >> "$DEPLOY_LOG"
log "audit" "appended rollback entry to $DEPLOY_LOG"

log "done" "rollback to $TAG complete"
